[package]
name = "hello_macro"
version = "0.1.0"
authors = ["Mike Morris <mikemorris@users.noreply.github.com>"]
edition = "2018"

[dev-dependencies]
hello_macro_derive = { path = "./hello_macro_derive" }
